### ISSUE TITLE
 rMSA for R 3.5

### ISSUE THREAD

**Issue by cvyaru** [mhahsler/rMSA#2]
Hello, I would need to install a version of rMSA for R 3.5. I am getting issues with the dependency "pwalign". Is there a legacy version that can still be installed? Thanks!

**Comment by mhahsler** [comment]
Hi, 

You can find a release that hopefully works with R 3.6 here:

https://github.com/mhahsler/rMSA/releases/tag/pre_pwalign 

You'll need to install it from the source.

Regards,
Michael

**Comment by cvyaru** [comment]
[like]  Yasser Bruno Ruiz Blanco reacted to your message:
________________________________
